#!/usr/bin/env node
// Scan codebase for TODO/FIXME/HACK/XXX comments
// Usage: node todo-scan.mjs [directory] [--json] [--vault <vault-path>]
// Zero dependencies

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join, relative, extname, basename } from 'path';

const args = process.argv.slice(2);
let dir = '.';
let format = 'text';
let vault = null;

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--json') format = 'json';
  else if (args[i] === '--vault') vault = args[++i];
  else if (!args[i].startsWith('-')) dir = args[i];
}

const SKIP_DIRS = new Set([
  'node_modules', '.git', 'vendor', 'dist', 'build', '.next',
  '__pycache__', '.venv', 'target', '.cache', 'coverage',
  '.obsidian', '.claude', '.agents',
]);

const CODE_EXTS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.py', '.rb', '.go', '.rs', '.java', '.swift', '.kt', '.cs', '.php',
  '.vue', '.svelte', '.css', '.scss', '.sass', '.less',
  '.sh', '.bash', '.zsh', '.fish',
  '.yaml', '.yml', '.toml', '.json', '.xml',
  '.c', '.cpp', '.h', '.hpp', '.m', '.mm',
  '.ex', '.exs', '.erl', '.hs', '.ml', '.clj',
  '.r', '.R', '.jl', '.dart', '.scala', '.groovy',
]);

const PATTERN = /\b(TODO|FIXME|HACK|XXX)\s*[:(]/i;
const PATTERN_SIMPLE = /\b(TODO|FIXME|HACK|XXX)\b/i;

function walk(dir) {
  const files = [];
  try {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (SKIP_DIRS.has(entry.name)) continue;
      if (entry.name.startsWith('.') && entry.isDirectory()) continue;
      const full = join(dir, entry.name);
      if (entry.isDirectory()) files.push(...walk(full));
      else if (CODE_EXTS.has(extname(entry.name))) files.push(full);
    }
  } catch {}
  return files;
}

const files = walk(dir);
const items = [];

for (const file of files) {
  const rel = relative(dir, file);
  let lines;
  try { lines = readFileSync(file, 'utf8').split('\n'); } catch { continue; }

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!PATTERN_SIMPLE.test(line)) continue;

    let type = 'todo';
    if (/FIXME/i.test(line)) type = 'fixme';
    else if (/HACK/i.test(line)) type = 'hack';
    else if (/XXX/i.test(line)) type = 'xxx';

    items.push({
      file: rel,
      line: i + 1,
      type,
      content: line.trim(),
    });
  }
}

const counts = { fixme: 0, todo: 0, hack: 0, xxx: 0 };
for (const item of items) counts[item.type]++;

if (items.length === 0) {
  console.log('No TODO/FIXME/HACK/XXX found.');
  process.exit(0);
}

if (format === 'json') {
  console.log(JSON.stringify({ total: items.length, counts, items }, null, 2));
} else {
  console.log('\n## Code TODOs\n');

  for (const [type, label] of [['fixme', 'FIXME — fix first'], ['todo', 'TODO'], ['hack', 'HACK — technical debt'], ['xxx', 'XXX']]) {
    const filtered = items.filter(i => i.type === type);
    if (filtered.length === 0) continue;
    console.log(`### ${label} (${filtered.length})\n`);
    for (const item of filtered) {
      console.log(`- [ ] \`${item.file}:${item.line}\` — ${item.content}`);
    }
    console.log('');
  }

  console.log(`### Summary`);
  console.log(`- ${counts.fixme} FIXMEs | ${counts.todo} TODOs | ${counts.hack} HACKs | ${counts.xxx} XXXs`);
  console.log(`- Scanned: ${files.length} files\n`);
}

// Write to vault
if (vault && existsSync(vault)) {
  const project = basename(process.cwd());
  const vaultFile = join(vault, '01 - Projects', project, 'code-todos.md');
  mkdirSync(join(vault, '01 - Projects', project), { recursive: true });

  const date = new Date().toISOString().split('T')[0];
  let md = `---\nid: code-todos\ntags: [project/${project}, todo, tracking]\ncreated: ${date}\nupdated: ${date}\n---\n\n`;
  md += `# Code TODOs — ${project}\n\n`;
  md += `> Auto-generated by \`/obsidian todo scan\`. Last scanned: ${date}.\n\n`;

  for (const [type, label] of [['fixme', 'FIXME (fix first)'], ['todo', 'TODO'], ['hack', 'HACK (technical debt)']]) {
    const filtered = items.filter(i => i.type === type);
    if (filtered.length === 0) continue;
    md += `## ${label}\n\n`;
    for (const item of filtered) {
      md += `- [ ] \`${item.file}:${item.line}\` — ${item.content}\n`;
    }
    md += '\n';
  }

  md += `## Summary\n- ${counts.fixme} FIXMEs | ${counts.todo} TODOs | ${counts.hack} HACKs\n`;

  writeFileSync(vaultFile, md);
  console.log(`Saved to vault: ${vaultFile}`);
}
